# Generated by Django 4.1.7 on 2023-02-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_refreshtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='last_fetched_month',
            field=models.IntegerField(default=0, verbose_name='Last month to be fetched'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_month_tweets',
            field=models.ManyToManyField(blank=True, related_name='_Last_Month_Tweets', to='core.tweet'),
        ),
        migrations.AddField(
            model_name='user',
            name='recent_tweets',
            field=models.ManyToManyField(blank=True, related_name='_Recent_Tweets', to='core.tweet'),
        ),
    ]
