# Generated by Django 4.1.7 on 2023-03-26 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_last_month_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='flu_application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Flu application+', to='core.application'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_month_prediction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Last month prediction+', to='core.prediction'),
        ),
    ]
